Added color logging and assert methods.

diff --git a/scripts/initialize_node_config b/scripts/initialize_node_config
--- a/scripts/initialize_node_config
+++ b/scripts/initialize_node_config
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 # Initialize the node configuration.
-# cur_path="$(dirname ${BASH_SOURCE[0]})"
-echo "$LOGGING_PREFIX Initializing node configuration for $NODE_TYPE @ $PG_NODE"
+cur_path="$(dirname ${BASH_SOURCE[0]})"
+source "$cur_path/common.sh"
+log:info "Initializing node configuration for $NODE_TYPE @ $PG_NODE"
 
 node_config_file=""
 config_target_file=""
@@ -24,12 +25,14 @@ proxy)
   node_config_file="/config/config_append_proxy"
   ;;
 *)
-  echo "$LOGGING_PREFIX Node configuration dose not exist for type $NODE_TYPE, error in condfig."
+  log:error "Node configuration dose not exist for type $NODE_TYPE, error in condfig."
   exit 1
   ;;
 esac
 
-cat "/config/config_append_internal_global" >> "$config_target_file" || exit 1
-cat "$node_config_file" >> "$config_target_file" || exit 1
+cat "/config/config_append_internal_global" >> "$config_target_file"
+assert $? "Failed to append internal global configuration to $config_target_file" || exit $?
+cat "$node_config_file" >> "$config_target_file"
+assert $? "Failed to append node configuration file $node_config_file to $config_target_file" || exit $?
 
-echo "$LOGGING_PREFIX Node configuration added to $config_target_file"
+log:info "Node configuration added to $config_target_file"
diff --git a/scripts/initialize_postgres_db b/scripts/initialize_postgres_db
--- a/scripts/initialize_postgres_db
+++ b/scripts/initialize_postgres_db
@@ -1,25 +1,27 @@
 #!/usr/bin/env bash
 # Initialize the postgres database.
 cur_path="$(dirname ${BASH_SOURCE[0]})"
-echo "$LOGGING_PREFIX Initializing database on node $PG_NODE"
+source "$cur_path/common.sh"
+log:info "Initializing database on node $PG_NODE"
 
 if [ "$RESET_DB" == "true" ] && [ -d "${PGDATA}" ]; then
   rm -R "${PGDATA}"
 fi
 
 if [ ! -f "${PGDATA}/postgresql.conf" ]; then
-  echo "$LOGGING_PREFIX Database configuration not found, calling initdb"
+  log:info "Database configuration not found, calling initdb"
 
   PG_PW_FILE=""
 
   if [ -z "$PGPASSWORD" ]; then
-    echo "$LOGGING_PREFIX WARNING: Database superuser password not found, DB is insecure."
+    log:warning "Database superuser password not found, DB is insecure."
     initdb \
       -D "${PGDATA}" \
       -U "${PGUSER}" \
-      --nodename="${PG_NODE}" || exit $?
+      --nodename="${PG_NODE}"
+      assert $? "Postgres init db failed, postgres database cannot be started." || exit $?
   else
-    echo "$LOGGING_PREFIX Database superuser password found, initializing db with password."
+    log:info "Database superuser password found, initializing db with password."
     PG_PW_FILE="/tmp/$(mktemp pgpass-XXXXX.pwd)"
     echo "${PGPASSWORD}" > "$PG_PW_FILE"
 
@@ -28,7 +30,8 @@ if [ ! -f "${PGDATA}/postgresql.conf" ]; then
       -D "${PGDATA}" \
       -U "${PGUSER}" \
       --nodename="${PG_NODE}" \
-      --pwfile="${PG_PW_FILE}" || exit $?
+      --pwfile="${PG_PW_FILE}"
+    assert $? "Postgres init db failed, postgres database cannot be started." || exit $?
   fi
 
   export PG_PW_FILE
@@ -36,23 +39,25 @@ if [ ! -f "${PGDATA}/postgresql.conf" ]; then
   source "$cur_path/initialize_networks" || exit $?
   source "$cur_path/initialize_node_config" || exit $?
 
-  echo "$LOGGING_PREFIX Database configuration initialized."
+  log:info "Database configuration initialized."
 else
-  echo "$LOGGING_PREFIX Database configuration found, init skipped."
+  log:info "Database configuration found, init skipped."
 fi
 
 # required for postgrs permissions.
 # the loaded values are actually set by kuberntes. :(
-echo "$LOGGING_PREFIX Set data folder permissions 0700"
+log:info "Set data folder permissions 0700"
 chmod -R 0700 ${PGDATA}
+assert $? "Failed to change data folder permissions" || exit $?
 
 # check for proxy.
 if [ "$PROXY_ENABLED" = "true" ]; then
   export PG_GTM_HOST="$PROXY_SERVICE"
-  echo "$LOGGING_PREFIX looking for GTM proxy host @ $PG_GTM_HOST..."
+  log:info "looking for GTM proxy host @ $PG_GTM_HOST..."
 else
-  echo "$LOGGING_PREFIX looking for GTM host @ $PG_GTM_HOST..."
+  log:info "looking for GTM host @ $PG_GTM_HOST..."
 fi
 
 # waiting for GTM.
-"$cur_path/wait_for_connection" "$PG_GTM_HOST" "$PG_GTM_PORT" || exit $?
+"$cur_path/wait_for_connection" "$PG_GTM_HOST" "$PG_GTM_PORT"
+assert $? "Error while waiting for connection. Deployment not ready." || exit $?
diff --git a/scripts/job_on_load b/scripts/job_on_load
--- a/scripts/job_on_load
+++ b/scripts/job_on_load
@@ -1,22 +1,15 @@
 #!/usr/bin/env bash
 
 cur_path="$(dirname ${BASH_SOURCE[0]})"
+source "$cur_path/common.sh"
 
 function log() {
   echo "$LOGGING_PREFIX" "$@"
 }
 
-function assert() {
-  if [ "$1" -ne 0 ]; then
-    log "ERROR: " "$@"
-    return $1
-  fi
-  return 0
-}
-
-log "Waiting for database to be ready..."
+log:info "Waiting for database to be ready..."
 "$cur_path/wait_for_connection" "$EXTERNAL_SERVICE" "$PG_PORT"
-assert $? "ERRROR: Failed while waiting for database service to start." || exit $?
+assert $? "Aborted, timed out while waiting for database to be ready @" "$EXTERNAL_SERVICE:$PG_PORT" || exit $?
 
 function is_initialized() {
   local dose_state_table_exist=""
@@ -48,54 +41,56 @@ function run_scripts_that_match() {
   local pattern="$1"
   local src_path="$(realpath "$2")"
 
-  log "Finding scripts that match pattern '$pattern' in folder '$src_path'"
+  log:info "Finding scripts that match pattern '$pattern' in folder '$src_path'"
   local scripts=""
   scripts="$(find "$src_path" -maxdepth 1 -name "$pattern" | sort)"
   scripts=($scripts)
 
   for fpath in "${scripts[@]}"; do
-    log "Executing script $fpath:"
+    log:info "Executing script $fpath:"
     local fname=$(basename "$fpath")
     local fileext=${fname##*.}
 
     case $fileext in
     sh)
-      source "$fpath"
-      assert $? "ERROR: Error while executing init script file $fpath. Exiting... " || return $?
+      chmod +x "$fpath"
+      assert $? "Failed to set executable permissions on $fpath" 
+      "$fpath"
+      assert $? "Failed when executing init script file $fpath. Exiting... " || return $?
       ;;
     sql)
       local sql_script=""
       sql_script=$(cat "$fpath")
       psql -c "$sql_script"
-      assert $? "ERROR: Error while executing init script file $fpath. Exiting... " || return $?
+      assert $? "Failed when executing init script file $fpath. Exiting... " || return $?
       ;;
     *)
-      assert 1 "ERROR: Cannot invoke filename with extention $fileext, skipping. Allowed [sql, sh]"
+      log:warning "Cannot invoke filename with extension $fileext, skipping. Allowed extensions [sql, sh]"
       ;;
     esac
   done
 }
 
 pg_isready
-assert $? "Cannot connect to remote database" || exit $?
+assert $? "Database Port is ready but cannot connect to remote database @" "$EXTERNAL_SERVICE:$PG_PORT" || exit $?
 
 is_initialized
 db_already_initialized=$?
 
 if [ $db_already_initialized -eq 0 ]; then
-  log "Database has not been initialized, calling init scripts.."
+  log:info "Database has not been initialized, calling init scripts.."
 
-  log "Invoking init scripts.."
+  log:info "Invoking init scripts.."
   run_scripts_that_match "init_*" "/load_scripts"
   assert $? "Initialization scripts failed, exiting." || exit $?
 
-  log "Creating db postgres-xl-helm state tables"
+  log:info "Creating db postgres-xl-helm state tables"
   initialize_pgxl_state
   assert $? "Failed to initialize database for postgres-xl helm chart state." || exit $?
 else
-  log "Database already initialized. Skipping init scripts."
+  log:info "Database already initialized. Skipping init scripts."
 fi
 
-log "Invoking startup scripts.."
+log:info "Invoking startup scripts.."
 run_scripts_that_match "startup_*" "/load_scripts"
 assert $? "Startup scripts failed, exiting." || exit $?
